### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by eugenekh81**
The game is done, please check
[PLAY](https://eugenekh81.github.io/js_2048_game/)

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
if we don't have any cells to merge then don't add another one

https://github.com/mate-academy/js_2048_game/assets/70220667/4e47e531-7f8f-422a-857a-dfcbc95fce78


2. I still should have the opportunity to move, I didn't lose :(
image

**Review by etojeDenys — CHANGES_REQUESTED** [review]
still not fixed 

https://github.com/mate-academy/js_2048_game/assets/70220667/ae4534a9-ca85-4e48-af9e-5509e093ba37
image

feel free to ask for some help in the chat with that

**Comment by eugenekh81** [comment]
> still not fixed
> 
> https://github.com/mate-academy/js_2048_game/assets/70220667/ae4534a9-ca85-4e48-af9e-5509e093ba37 image
> 
> feel free to ask for some help in the chat with that

it's not working like this on my end  - when the tiles are not moved, new tile is not generated
and if there are moves available, it doesn't end the game, can we discuss this ?

**Comment by eugenekh81** [comment]
fixed, deployed

**Pull request closed without merging**
