### PR TITLE
solution

### PR DESCRIPTION
**Pull request by maksym-kostetskyi**
https://maksym-kostetskyi.github.io/js_2048_game/

### CODE REVIEW

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Please provide demo link in PR description.
Also suggest to make some refactoring.
- write magic numbers in variables. looks like it can be one variable something like const GAME_SIZE = 4 and use it in all places to replace 4 , 16, 3 hardocoded numbers.
- move function looks like rather similar. try to group same or similar logic in functions. it can reduce amount of code and make code more cleaner

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Thanks for demo link.
Found a couple bugs.
- after start game should appear two cells wiht number.
- after any move if no cells for merge and any cell wasn't moved - new cell shouldn't appear.

**Review by maxim2310 — CHANGES_REQUESTED** [review]
find one bug, please fix it before approval 
restart must start new game immediately

**Review by maxim2310 — APPROVED** [review]
Good job!!!

**Pull request closed without merging**
