### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by nazardudnyk**

### CODE REVIEW

**Review by lerastarynets — CHANGES_REQUESTED** [review]
Unfortunately, your project is not reachable via the demo link(

**Review by lerastarynets — CHANGES_REQUESTED** [review]
Pls ask for help in **fe_chat** if you don't understand something

**Comment by nazardudnyk** [comment]
> Pls ask for help in **fe_chat** if you don't understand something

@lerastarynets 
-  https://nazardudnyk.github.io/js_2048_game/

**Comment by nazardudnyk** [comment]
> Great work! Sometimes the new number is added when the game field doesn't change, consider adding a new number just if the cells were moved

did you mean that?

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Make sure to deploy your page

**Comment by nazardudnyk** [comment]
> Make sure to deploy your page
Знімок екрана 2023-12-13 о 13 08 05
Знімок екрана 2023-12-13 о 13 07 25

@anastasiiavorobiova 

why does the page work correctly when running the npm start command, but when opened through the Demo link, it does not work correctly?

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Make sure to deploy your page! Feel free to ask for help in the chat or use this instruction https://mate-academy.github.io/layout_task-guideline/#codegit-addcode-to-prepare-changed-files-for-saving

**Pull request closed without merging**
